// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbXxojE12I9MmIPxd92b-Z2EV3_nHZR8',
    appId: '1:171851347772:web:2d305cf38a1bdac4b91039',
    messagingSenderId: '171851347772',
    projectId: 'social-media-helper-14c93',
    authDomain: 'social-media-helper-14c93.firebaseapp.com',
    storageBucket: 'social-media-helper-14c93.firebasestorage.app',
    measurementId: 'G-SL0PYJSFS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8gAD-iDWUQJ6CcR1VmwECIvIE97Fxuk',
    appId: '1:171851347772:android:f18cea16be31f167b91039',
    messagingSenderId: '171851347772',
    projectId: 'social-media-helper-14c93',
    storageBucket: 'social-media-helper-14c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsOTvFqx4OUaNh5NlxuSQDXOcwj6FpKtU',
    appId: '1:171851347772:ios:71c35c51469a74c1b91039',
    messagingSenderId: '171851347772',
    projectId: 'social-media-helper-14c93',
    storageBucket: 'social-media-helper-14c93.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsOTvFqx4OUaNh5NlxuSQDXOcwj6FpKtU',
    appId: '1:171851347772:ios:71c35c51469a74c1b91039',
    messagingSenderId: '171851347772',
    projectId: 'social-media-helper-14c93',
    storageBucket: 'social-media-helper-14c93.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkbXxojE12I9MmIPxd92b-Z2EV3_nHZR8',
    appId: '1:171851347772:web:0e88478bb73cdae8b91039',
    messagingSenderId: '171851347772',
    projectId: 'social-media-helper-14c93',
    authDomain: 'social-media-helper-14c93.firebaseapp.com',
    storageBucket: 'social-media-helper-14c93.firebasestorage.app',
    measurementId: 'G-G15D8WGHHR',
  );
}
